maps:
  lobby: world
  bedwars: bedwars
  list:
    - lobby
    - bedwars
bedwars:
  players: 4
  timeout-minutes: 3
  timeout-min-players: 2
  spawnpoints:
    - {x: 0, y: 65, z: 0}
    - {x: 10, y: 65, z: 0}
